<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="Assets\Images\icon.icns">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="Assets\Info.plist">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="Avalonia.Svg.Skia"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="System.Drawing.Common"/>
        <PackageReference Include="Xaml.Behaviors.Avalonia"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Remove="ViewModels\PrintSettingsViewModel.cs"/>
        <Compile Remove="ViewModels\ActionsTabSaveModelViewModel.cs"/>
        <Compile Remove="ViewModels\ActionsTabPrintViewModel.cs"/>
        <Compile Remove="DataStorage\DataModels\PrintSettingsDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabPrintDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabImportFileDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabFileInfoDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabDrawingTemplateDataModel.cs"/>
        <Compile Update="Views\Pages\ActionsPageView.axaml.cs">
            <DependentUpon>ActionsPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\HistoryPageView.axaml.cs">
            <DependentUpon>HistoryPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\HomePageView.axaml.cs">
            <DependentUpon>HomePageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\MacrosPageView.axaml.cs">
            <DependentUpon>MacrosPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\MainView.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ProcessPageView.axaml.cs">
            <DependentUpon>ProcessPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ReporterPageView.axaml.cs">
            <DependentUpon>ReporterPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\SettingsPageView.axaml.cs">
            <DependentUpon>SettingsPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionCustomPropertiesView.axaml.cs">
            <DependentUpon>ActionCustomPropertiesView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionDrawingTemplateView.axaml.cs">
            <DependentUpon>ActionDrawingTemplateView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionFileInfoView.axaml.cs">
            <DependentUpon>ActionFileInfoView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionImportFileView.axaml.cs">
            <DependentUpon>ActionImportFileView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionMacrosView.axaml.cs">
            <DependentUpon>ActionMacrosView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionPrintView.axaml.cs">
            <DependentUpon>ActionPrintView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionSaveDrawingView.axaml.cs">
            <DependentUpon>ActionSaveDrawingView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Actions\ActionSaveModelView.axaml.cs">
            <DependentUpon>ActionSaveModelView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BatchProcess3.Core\BatchProcess3.Core.csproj"/>
    </ItemGroup>
</Project>
