<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia"/>
        <PackageReference Include="Avalonia.Controls.DataGrid"/>
        <PackageReference Include="Avalonia.Svg.Skia"/>
        <PackageReference Include="Avalonia.Themes.Fluent"/>
        <PackageReference Include="Avalonia.Fonts.Inter"/>
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="System.Drawing.Common"/>
        <PackageReference Include="Xaml.Behaviors.Avalonia"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\MainWindow.axaml.cs">
            <DependentUpon>MainView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Remove="ViewModels\PrintSettingsViewModel.cs"/>
        <Compile Remove="ViewModels\ActionsTabSaveModelViewModel.cs"/>
        <Compile Remove="ViewModels\ActionsTabPrintViewModel.cs"/>
        <Compile Remove="DataStorage\DataModels\PrintSettingsDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabPrintDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabImportFileDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabFileInfoDataModel.cs"/>
        <Compile Remove="DataStorage\DataModels\ActionsTabDrawingTemplateDataModel.cs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\BatchProcess3.Core\BatchProcess3.Core.csproj"/>
    </ItemGroup>
</Project>
